runtime: nodejs20
env: standard
instance_class: F1

includes:
  - env_variables.yaml

handlers:
  - url: /.*
    script: auto
    secure: always

automatic_scaling:
  min_instances: 0
  max_instances: 1
  min_idle_instances: 0
  max_idle_instances: 1
